name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3-pip openjdk-17-jdk unzip zip wget libffi-dev libssl-dev

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install --user Cython buildozer
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build APK
      run: |
        export PATH=$HOME/.local/bin:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: ./bin/*.apk
